trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  solutionName: 'Lunitor.MediaServerMonitor'

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.sln'
    feedsToUse: 'select'
    vstsFeed: '650d259c-cad6-4457-aead-eedb5fe6acba'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build $(buildConfiguration)'
  inputs:
    command: 'build'
    projects: '**/*.sln'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish $(buildConfiguration)'
  inputs:
    command: 'publish'
    projects: '**/*.Server.csproj'
    publishWebProjects: false
    arguments: '--configuration $(BuildConfiguration) --no-build --output $(Build.ArtifactStagingDirectory)/$(solutionName)/Deploy'
    modifyOutputPath: true
    zipAfterPublish: true

- publish: '$(Build.ArtifactStagingDirectory)/$(solutionName)/Deploy'
  artifact: $(solutionName)
